# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui/drink.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Drink(object):
    def setupUi(self, Drink):
        Drink.setObjectName("Drink")
        Drink.resize(300, 500)
        Drink.setMinimumSize(QtCore.QSize(300, 500))
        Drink.setMaximumSize(QtCore.QSize(300, 500))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        Drink.setFont(font)
        self.list = QtWidgets.QComboBox(Drink)
        self.list.setGeometry(QtCore.QRect(10, 30, 280, 60))
        self.list.setEditable(False)
        self.list.setCurrentText("")
        self.list.setObjectName("list")
        self.name = QtWidgets.QLineEdit(Drink)
        self.name.setGeometry(QtCore.QRect(20, 130, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet("border: 5px solid;")
        self.name.setText("")
        self.name.setFrame(False)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.pump = QtWidgets.QPushButton(Drink)
        self.pump.setGeometry(QtCore.QRect(40, 250, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pump.setFont(font)
        self.pump.setObjectName("pump")
        self.purge = QtWidgets.QPushButton(Drink)
        self.purge.setGeometry(QtCore.QRect(160, 250, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.purge.setFont(font)
        self.purge.setObjectName("purge")
        self.ok = QtWidgets.QPushButton(Drink)
        self.ok.setGeometry(QtCore.QRect(100, 380, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ok.setFont(font)
        self.ok.setObjectName("ok")

        self.retranslateUi(Drink)
        QtCore.QMetaObject.connectSlotsByName(Drink)

    def retranslateUi(self, Drink):
        _translate = QtCore.QCoreApplication.translate
        Drink.setWindowTitle(_translate("Drink", "Dialog"))
        self.pump.setText(_translate("Drink", "Pomper"))
        self.purge.setText(_translate("Drink", "Purger"))
        self.ok.setText(_translate("Drink", "OK"))
import resources_rc
