# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui/finished.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Finished(object):
    def setupUi(self, Finished):
        Finished.setObjectName("Finished")
        Finished.resize(1024, 600)
        self.titleText = QtWidgets.QLineEdit(Finished)
        self.titleText.setGeometry(QtCore.QRect(0, 70, 1024, 70))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.titleText.setFont(font)
        self.titleText.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.titleText.setFrame(False)
        self.titleText.setAlignment(QtCore.Qt.AlignCenter)
        self.titleText.setReadOnly(True)
        self.titleText.setObjectName("titleText")
        self.newDrink = QtWidgets.QPushButton(Finished)
        self.newDrink.setGeometry(QtCore.QRect(332, 250, 360, 100))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.newDrink.setFont(font)
        self.newDrink.setStyleSheet("border: 10px solid;\n"
"background-color: rgb(172, 183, 255);\n"
"border-color: rgb(55, 56, 115);")
        self.newDrink.setAutoDefault(False)
        self.newDrink.setDefault(False)
        self.newDrink.setFlat(False)
        self.newDrink.setObjectName("newDrink")

        self.retranslateUi(Finished)
        QtCore.QMetaObject.connectSlotsByName(Finished)

    def retranslateUi(self, Finished):
        _translate = QtCore.QCoreApplication.translate
        Finished.setWindowTitle(_translate("Finished", "Dialog"))
        self.titleText.setText(_translate("Finished", "Votre boisson est prête!"))
        self.newDrink.setText(_translate("Finished", "Nouvelle boisson!"))
