# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui/loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Loading(object):
    def setupUi(self, Loading):
        Loading.setObjectName("Loading")
        Loading.resize(1024, 600)
        self.glass = QtWidgets.QLabel(Loading)
        self.glass.setGeometry(QtCore.QRect(450, 170, 100, 125))
        self.glass.setStyleSheet("border-image: url(:/Logo/glass.gif) 0 0 0 0 stretch stretch;")
        self.glass.setText("")
        self.glass.setObjectName("glass")
        self.conveyor = QtWidgets.QLabel(Loading)
        self.conveyor.setGeometry(QtCore.QRect(256, 295, 512, 100))
        self.conveyor.setStyleSheet("border-image: url(:/Logo/conveyor.gif) 0 0 0 0 stretch stretch;")
        self.conveyor.setText("")
        self.conveyor.setObjectName("conveyor")
        self.step = QtWidgets.QLineEdit(Loading)
        self.step.setGeometry(QtCore.QRect(0, 440, 1024, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.step.setFont(font)
        self.step.setStyleSheet("background: transparent;")
        self.step.setFrame(False)
        self.step.setAlignment(QtCore.Qt.AlignCenter)
        self.step.setReadOnly(True)
        self.step.setObjectName("step")

        self.retranslateUi(Loading)
        QtCore.QMetaObject.connectSlotsByName(Loading)

    def retranslateUi(self, Loading):
        _translate = QtCore.QCoreApplication.translate
        Loading.setWindowTitle(_translate("Loading", "Dialog"))
        self.step.setText(_translate("Loading", "Steps..."))
import resources_rc
