# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 70, 1024, 530))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContents = QtWidgets.QWidget()
        self.scrollContents.setGeometry(QtCore.QRect(0, 0, 1024, 530))
        self.scrollContents.setObjectName("scrollContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollContents)
        self.titleText = QtWidgets.QTextEdit(self.centralwidget)
        self.titleText.setEnabled(True)
        self.titleText.setGeometry(QtCore.QRect(0, 10, 1024, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.titleText.setFont(font)
        self.titleText.setAcceptDrops(True)
        self.titleText.setAutoFillBackground(False)
        self.titleText.setStyleSheet("background:transparent;")
        self.titleText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.titleText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.titleText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.titleText.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titleText.setObjectName("titleText")
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(950, 0, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.settings.setFont(font)
        self.settings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.settings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logo/gear_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon)
        self.settings.setIconSize(QtCore.QSize(64, 64))
        self.settings.setCheckable(False)
        self.settings.setDefault(False)
        self.settings.setFlat(True)
        self.settings.setObjectName("settings")
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.titleText.setHtml(_translate("Main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600; color:#000000;\">Sélectionnez votre boisson</span></p></body></html>"))
import resources_rc
